### ISSUE TITLE
Create a C++ array class

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#152]
Create a C++ array class, Like std::vector but a fixed width.  it should also support bounds checking and be GC allocatable.  See the TODO comment in `pz_data.h`.

This bug has the no-domain-knowledge tag but there's slight knowledge required about GC. I can provide any assistance / make it GCable. It's actually fairly easy.

**Comment by AlaskanEmily** [comment]
What are the differences between this and std::array? Is this dynamically allocated of a size which is immutable after construction, but not known at compile time?

**Comment by PaulBone** [comment]
The main thing is that it should work with the GC. But reading my comment above it sounds like fixed size is okay. I think I was going to use it for storing things within the Module and/or ModuleLoading classes. So it should be GC allocatable (we have a placement-new constructor and a class to override for that). It should place all its storage (relevant if it grows/shrinks) in the GC heap. Don't worry about tracing, for now the GC is conservative.

**Comment by PaulBone** [comment]
Hi @AlaskanEmily I implemented a very basic GC-able and bounds-checked array 
in e1be353. I still want to do the same for an auto-growing vector and add C++ liberators to both of them. But you can review it if you like, since you asked about this bug.
