### ISSUE TITLE
Decide on terminology for module system

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#168]
I kicked around the idea of having "modules" and "packages". A module is a compilation unit and several will be linked together to form a package, the package is loaded at runtime and linked into a process then.  References between modules maybe cyclic, packages may not have cyclic references. I feel like "package, you know like in Java" is a bit too verbose. Maybe we need a plasma-themed name for this?

**Comment by ACleverDisguise** [comment]
Distinguishing between compilation units and physical grouping is a wise idea, an idea I first saw dealt with that way with Dylan.  It had the same rules, in fact: you could have circular dependencies in modules, but packages had to be strictly hierarchical.

What's the issue with just calling them "modules" and "packages", though?

**Comment by PaulBone** [comment]
Just a minor worry that by using the generic terms people might misunderstand that they're distinct things. I just want to consider whether there might be some more useful terms, and bonus points if its the right type of whimsical, without making it harder to understand.

**Comment by PaulBone** [comment]
So I think the following concepts are what we want?

# .p files are modules (source code)

A developer writes source code in .p files.  Each .p file corresponds to exactly one Plasma Module. It has a single `module` declaration at the beginning.  The file name may be reuqired to match the module name in some specific way but I don't know yet.

# .pm (maybe .pzm) files are modules too.

Each module (.p file) is compiled to exactly one .pm file, Users will hardly ever interact with these. Maybe they'll be put in some .plz directory out of the way.

# .pz files are "Plasma packages"

Multiple .pm files can be combined (linked) into a single package (.pz file). These can be executed (if they have a defined entrypoint) or dynamically linked.  Dependencies between .pz files must not be circular, they may be circular between .pm files within the same .pz file.

# .pi files

Plasma interface files.  These files are generated from .p files and can be read by

**Comment by brendanzab** [comment]
Rust has 'crates' which seem to be what you are calling 'packages' (I think 'package' is an okay name, fwiw). Here's the chapter in the [Rust book](https://doc.rust-lang.org/book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html). Modules are within those crates, and can be mutually recursive. One cool thing about Rust is that you can have [multiple versions of the same crate in a single project](https://stackoverflow.com/a/51722134) - I think because each are given a unique hash or something like that. This is really nice, because it reduces the chance of getting into the 'dependency hell' that you always seem to run into in the Cabal or OPAM ecosystems.

**Comment by PaulBone** [comment]
Right. That's an important point about multiple versions.  I've certainly heard about the issues people experience with Cabal. There's probably other things we can do to ensure that multiple versions can be used by a single program, eg module local state may need to be avoided and values of the same data type mustn't be passed between different instances of the same module. (they should be represented as different data types).

**Comment by brendanzab** [comment]
Yeah, you do run into issues if you accidentally confuse data types between different library versions, but I think that's a far better problem to have than two libraries failing to build because a common ancestor dependency couldn't be found. This could be also mitigated by better error messages - something that Rust could improve on.

**Comment by ACleverDisguise** [comment]
Going with my own (distant) experience with Dylan, I'm going to do some conceptual mapping.

To me it looks like your .pm files are modules in Dylan and .pz are libraries.  Modules are the unit of access control in Dylan while libraries are the unit of PACKAGING.  Libraries were in turn made into .so/.a/.dll/etc. depending on their intended use.  An application was generally formed from the linking of one or more libraries (either static or dynamic) with a runtime wrapper.

The fact that your divisions above remind me of Dylan (right down to the lack of circular references among .pz files, but .pm allows them) kind of makes me think this is a good design.  I was probably at my happiest as a programmer in the first stage of my programming life using Dylan.

**Comment by PaulBone** [comment]
> To me it looks like your .pm files are modules in Dylan and .pz are libraries. Modules are the unit of access control in Dylan while libraries are the unit of PACKAGING. Libraries were in turn made into .so/.a/.dll/etc. depending on their intended use. An application was generally formed from the linking of one or more libraries (either static or dynamic) with a runtime wrapper.

Without knowing Dylan this is correct to my knowledge.  Including access control which I didn't mention above (I guess it seemed obvious to me).  Modules is also the unit of separate compilation. (@brendanzab may note that this is different from Rust, I don't care for rust's mostly-lack of separate compilation).

> The fact that your divisions above remind me of Dylan (right down to the lack of circular references among .pz files, but .pm allows them) kind of makes me think this is a good design. I was probably at my happiest as a programmer in the first stage of my programming life using Dylan.

:-D Plasma has been in development for 4+ years, in my spare time. While that's painfully slow in some ways it's also allowed me to take the time and think about things / let them tick over in my mind before committing to them. I think slow-and-steady pace is the reason I'm landing on good designs (at least I think they're good, different strokes for different folks etc).

**Comment by PaulBone** [comment]
With some feedback from CcxWrk and ttmrichter on IRC:

 * We'll call packages "libraries" or "programs" rather than packages. Packaging software for distribution is something that should exist as a separate step. 
 * We'll use .po for compiled modules (plasma output / plasma object).
 * Somehow we'll want to support single-file distribution, this may work in degrees, we can consider more of that in the future, including its interaction with native code.
 * Somehow we'll want to be able to interface with foreign code and have that work within the module system.  The easy way is probably to dlload .so files as needed, eg zlib.so, then call symbols there. But there's probably other more complex situations where the programmer provides a chunk of foreign code that we need to compile and distribute.  Having a good FFI is important so this will need some more consideration.

**Comment by PaulBone** [comment]
Okay, that's decided then, closing this bug.

**Comment by PaulBone** [comment]
CcxWrk pointed out that packaging really is about distributing software.  But our "packages" above are about building it.  We've done some brainstorming on IRC and think that "Plasma balls" are what the linking step builds and perhaps the extension is .pb or maybe .pzb
