### ISSUE TITLE
Change variable binding syntax

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#170]
At the moment variable bindings allow a variable to be available after branching control flow if all paths either bind it or return early (not implemented):

    if (...) { 
        x = ...
    } else {
        x = ...
    }
    print!(x)   % We can use x here.

But it was pointed out to me that this is unintuitive, by more than one
person.  In my own experience this is okay (it's how Mercury works, and no
one seems to worry about it / notice it there).  But it seems I have some biases and instead we'll implement it as:

    val x
    if (...) { 
        x = ...
    } else {
        x = ...
    }
    print!(x)   % We can use x here.

And track that work in this bug.

**Comment by brendanzab** [comment]
Yeah, this is pretty much how Rust does it!

```rust
let x;
if ... {
    x = ...;
} else {
    x = ...;
}
println!("{}", x);
```

**Comment by PaulBone** [comment]
> Yeah, this is pretty much how Rust does it!
> 

I presume that:
```rust
let x; // `x` is uninitialized here
if ... {
    x = ...;
} else {
    not_x = ...;
}
println!("{}", x);
```

Is not legal.
