### ISSUE TITLE
Plasma fails to build with mmc 14.01.1-3

### ISSUE THREAD

**Issue by vmchale** [PlasmaLang/plasma#199]
When trying to compile with `mmc` I get:

```
asm.m:076: In clause for predicate `prepare_map'/5:
asm.m:076:   error: undefined predicate `return_vertices_in_to_from_order'/2.
** Error making `Mercury/reg.gc/x86_64-pc-linux-gnu/Mercury/cs/asm.c'.
Makefile:199: recipe for target 'src/plzasm' failed
make: *** [src/plzasm] Error 1
```

This is on Ubuntu 18.04 LTS; I'm using the mmc from the `mercury-recommended` package provided by your ppa.

`mmc --version` gives: 

```
Mercury Compiler, version 14.01.1-3, configured for x86_64-pc-linux-gnu
Copyright (C) 1993-2014 The University of Melbourne
```

Thanks!

**Comment by PaulBone** [comment]
Happy to fix this. It's supposed to work. But for a quick-fix try mercury-rotd-recommended as that's what I've been using.

**Comment by PaulBone** [comment]
@vmchale I believe this should fix the build problem you had. Thanks for letting us know, really appreciate it.
