### ISSUE TITLE
Installing fails when asciidoc is not installed

### ISSUE THREAD

**Issue by jimbxb** [PlasmaLang/plasma#404]
As the title says, attempting to install Plasma without assciidoc installed causes the `install` rule to fail.

Steps to recreate:
0. ensure asciidoc is not installed
1. run `make install`

Make should report an error similar to the following:
```
install -d /usr/local/bin
install -d /usr/local/share/doc/plasma

Warning: asciidoc not found, not building documentation.
--------------------------------------------------------

touch .docs_warning
cd docs/ ; for FILE in *.txt *.html; do \
        install $FILE /usr/local/share/doc/plasma; \
done
install: cannot stat '*.html': No such file or directory
make: *** [Makefile:133: install_docs] Error 1
```

**Comment by PaulBone** [comment]
Yes, I'd say that's the problem.  This should continue the installation just without installing documentation.  Ideally there should be a warning that documentation is not installed with a link to the website where it can be read.
