### ISSUE TITLE
plasmalang.org is suspended

### ISSUE THREAD

**Issue by patrick-nicodemus** [PlasmaLang/plasma#462]
When I visit plasmalang.org I get a warning that the project website has been suspended.

> Domain Suspension
> Registrant Information Verification Failure

> ICANN, the Internet Corporation for Assigned Names and Numbers, requires us to ask you as a Registrant of a domain name to verify your contact information for this domain with your provider. As a Registrant of a domain name, a new domain registration or changes to the first name, last name, contact address or email address of an existing domain name, requires verification of the information within 15 days. Since you failed to update the Registrant contact information, this domain name no longer resolves. For your domain to operate and resolve normally, please update your contact information with your domain provider and resend the verification email to yourself, and complete the verification process. Failure to provide accurate contact information could result in your domain being deleted. For more information on updating your contact information please contact your domain service provider.

> Enter the text displayed in the image below, then click the resend button to have another verification email sent to you.

**Comment by PaulBone** [comment]
Thanks Patrick.

It looks like the DNS registrar has the wrong e-mail address on file.  I'm trying to resolve it now.

**Comment by PaulBone** [comment]
Seems to be working now.
