### ISSUE TITLE
Provide toolchain setup instructions

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#8]
Provide detailed instructions for setting up Mercury, asciidoc, git, vim etc so it's easy to have the same experience I do.

**Comment by sullyj3** [comment]
Is there a vim ftplugin and syntax highlighter?

**Comment by PaulBone** [comment]
Assigning @Gertm because I know he started working on this.

**Comment by PaulBone** [comment]
> Is there a vim ftplugin and syntax highlighter?
> Edit: For plasma, I mean.

Hi, I came across this comment today. There is now a vim syntax highlighter.  file type detection is done with modelines for now.

https://github.com/PlasmaLang/vim

**Comment by PaulBone** [comment]
Hi Gertm, we have the [getting started guide](https://plasmalang.org/docs/getting_started.html) that you wrote. Do you think it's good enough for now? shall we close this issue?

In the future we probably want to break getting started into clearer streams eg: "if you have Debian/ubuntu" etc and make the navigation through it really clear. Maybe we don't need to do that now. So aside from that I wonder what else we may want now?

**Comment by Gertm** [comment]
Hi,

I do think it is good enough for now yeah.
Once we get the other documentation streamlined, we can maybe still work on
this.

But you can close this, yes.

**Comment by PaulBone** [comment]
Okay cool.
