### ISSUE TITLE
Make building the documentation optional

### ISSUE THREAD

**Issue by PaulBone** [PlasmaLang/plasma#96]
The "all" make target builds the documentation, but if someone is happy using the online docs and doesn't want to install asciidoc, it should be optional.

Hi @Gertm  / others, I'd like your perspective.  Should the "all" target build the docs but we add a new target for "progs" or something.  Or should we seperate the docs from the "all" target?

**Comment by Gertm** [comment]
I would leave it out of the default build. Or at least not fail the build when asciidoc (or asciidoctor) isn't found. Maybe have a 'make complete' for source + documentation?

How likely are people to use the local copy of the documentation instead of the online version anyway?

**Comment by PaulBone** [comment]
> I would leave it out of the default build. Or at least not fail the build when asciidoc (or asciidoctor) isn't found. Maybe have a 'make complete' for source + documentation?

Okay, I'll look if we can avoid failing if it's not found.  and otherwise introduce a "complete" target.

> How likely are people to use the local copy of the documentation instead of the online version anyway?

IMHO Only if they're editing it.  And maybe later on if people install Plasma they may wish to install the docs locally so they're available offline.

**Comment by Gertm** [comment]
Pretty sure in today's day and age, everybody just uses the online version.

**Comment by PaulBone** [comment]
> Pretty sure in today's day and age, everybody just uses the online version.

I don't, particularly when good info pages or similarly-good offline format is available, and in some cases just a "man fprintf" or whatever away.
